// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    ENDPOINT: "https://scpokct4hvg6re4zcqk7eo6iwe.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    REGION: "ap-southeast-2",
    AUTH_TYPE: "API_KEY"
};

export default awsmobile;